apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: doc-query
data:
  VECTOR_DB: "redis"
  # -----
  # Cloud-based Redis may not work well as they may not have the required modules.
  # -----
  # REDIS_HOST: "redis-cluster.sozjoz.0001.use1.cache.amazonaws.com"
  REDIS_HOST: "doc-redis.doc-query.svc.cluster.local"
  REDIS_PORT: "6379"
