services:
  doc_redis:
    image: redis/redis-stack-server:latest
    container_name: doc_redis
    ports:
    - 6379:6379
    volumes:
    - data:/data
    restart: always

  doc_backend:
    build: ./backend
    image: doc_backend:latest
    container_name: doc_backend
    volumes:
      - ./backend:/app
    ports:
      - "8003:8003"
    depends_on:
      - doc_redis
    env_file:
      - .env

  doc_frontend:
    build: ./frontend
    image: doc_frontend:latest
    container_name: doc_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3003:3003"
    depends_on:
      - doc_backend
    stdin_open: true
    tty: true

volumes:
  data:
