[browser]
#serverAddress = "0.0.0.0"
#serverPort = 443
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false

[global]
developmentMode = false

[theme]
base="dark"
primaryColor="#4bcdff"
backgroundColor="#05055a"
secondaryBackgroundColor="#2774cb"
