apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frontend-secret
  namespace: doc-query
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: frontend-secrets
  data:
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: doc_query_openai_keys
      property: OPENAI_API_KEY
  - secretKey: OPENAI_ORGANIZATION_ID
    remoteRef:
      key: doc_query_openai_keys
      property: OPENAI_ORGANIZATION_ID